//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WargaminAPI.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WargaminAPI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tjyua9cZxQCewpTUhLXIMc/JjuntTbkNpEo5o5JbVRI+rnuvS0oPrkh787UtzajRCzN0dnCVYMuCm24DtdGJXiWBrGc86hRrTaeZypXOawg=.
        /// </summary>
        internal static string application_id {
            get {
                return ResourceManager.GetString("application_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.worldoftanks.ru/wot/clans/info/?application_id=.
        /// </summary>
        internal static string uri_get_clan {
            get {
                return ResourceManager.GetString("uri_get_clan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.worldoftanks.ru/wot/clans/list/?application_id=.
        /// </summary>
        internal static string uri_get_clan_by_name {
            get {
                return ResourceManager.GetString("uri_get_clan_by_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.worldoftanks.ru/wot/account/info/?application_id=.
        /// </summary>
        internal static string uri_get_stat {
            get {
                return ResourceManager.GetString("uri_get_stat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.worldoftanks.ru/wot/clanratings/clans/?application_id=.
        /// </summary>
        internal static string uri_get_stat_clan {
            get {
                return ResourceManager.GetString("uri_get_stat_clan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.worldofwarships.ru/wows/account/info/?application_id=.
        /// </summary>
        internal static string uri_get_stat_WOW {
            get {
                return ResourceManager.GetString("uri_get_stat_WOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.worldoftanks.ru/wot/account/list/?application_id=.
        /// </summary>
        internal static string url_find_player {
            get {
                return ResourceManager.GetString("url_find_player", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на https://api.worldofwarships.ru/wows/account/list/?application_id=.
        /// </summary>
        internal static string url_find_player_WOW {
            get {
                return ResourceManager.GetString("url_find_player_WOW", resourceCulture);
            }
        }
    }
}
